# Generated by Django 4.2.10 on 2024-04-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineform',
            name='number_of_booths',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=20),
        ),
    ]
