# Generated by Django 4.2.10 on 2024-04-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Expo_app', '0002_onlineform_number_of_booths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boothallocation',
            name='expocode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Expo_app.onlineform'),
        ),
    ]
