# Generated by Django 4.2.10 on 2024-03-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expo_app', '0002_alter_onlineform_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineform',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
