# Generated by Django 4.2.10 on 2024-04-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expo_app', '0003_alter_boothallocation_expocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boothallocation',
            name='user',
        ),
        migrations.AddField(
            model_name='boothallocation',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
