# Generated by Django 4.2.10 on 2024-03-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expo_app', '0004_alter_onlineform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktickets',
            name='mobile',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='booktickets',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
